name: Practice-deployment
on: push 
jobs:
    stage_one:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3 
            - name: Install ndoejs 
              uses: actions/setup-node@v3 
              with: 
                node-version: '18'
            - name: Install dependency 
              run: npm ci 
            
            - name: do the testing
              run: npm test
    stage_two:
        needs: stage_one
        runs-on: ubuntu-latest
        steps:
            - name: Build the deployment
              run: npm run build
            - name: deploy the build
              run: echo "deploying the code ....."
            