name: First-action 
on: workflow_dispatch
jobs:
    first-job:
        runs-on: Ubuntu:latest 
        steps:
            - name: npm install 
              run: npm i 
            - name: npm run build 
              run: npm run build 