name: Deploy website

on:
  push:
    branches:
      - dev

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('01 Starting Project/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: 01 Starting Project

      - name: Test code
        run: npm run test
        working-directory: 01 Starting Project


  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: 01 Starting Project

      - name: Build code
        run: npm run build
        working-directory: 01 Starting Project

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: 01 Starting Project/dist


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: website-build
          path: ./dist

      - name: Deploy
        run: echo "deploying...."