name: Practice-deployment

on:
  push:
    branches:
      - main

jobs:
  stage_one:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependency
        run: npm ci

      - name: Do the testing
        run: npm test

  stage_two:
    needs: stage_one
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependency
        run: npm ci

      - name: Build the deployment
        run: npm run build

      - name: Deploy the build
        run: echo "deploying the code ....."
#     stage_two:
#         needs: stage_one
#         runs-on: ubuntu-latest
#         steps:
#             - name: Build the deployment
#               run: npm run build
#             - name: deploy the build
#               run: echo "deploying the code ....."
            

